{
 "title": "ArcGIS Enterprise",
 "tags": [ "arcgis" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "ArcGIS Enterprise services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"portal for arcgis\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"running\"}*4) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"unknown\"}*8)",
     "legendFormat": "Portal for ArcGIS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"portal for arcgis\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"running\"}*4) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"portal for arcgis\", state=\"unknown\"}*8)",
     "legendFormat": "Portal for ArcGIS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"arcgis data store\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"arcgis data store\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"arcgis data store\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"arcgis data store\", state=\"running\"}*4) + scalar(windows_service_state{name=\"arcgis data store\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"arcgis data store\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"arcgis data store\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"arcgis data store\", state=\"unknown\"}*8)",
     "legendFormat": "ArcGIS Datastore"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"running\"}*4) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"w3svc\", job=\"apo34wv.teide.int\", state=\"unknown\"}*8)",
     "legendFormat": "Web adaptor - Portal"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - arcgis_backup_created_date_seconds{type=\"incremental\"} < 648000 and arcgis_backup_size_bytes{type=\"incremental\"} > 0",
     "legendFormat": "Backup - Incremental"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(argis_expiration_license_seconds - time() <  5184000) or vector(0)",
     "legendFormat": "Licenses expiration"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"arcgis server\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"arcgis server\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"arcgis server\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"arcgis server\", state=\"running\"}*4) + scalar(windows_service_state{name=\"arcgis server\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"arcgis server\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"arcgis server\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"arcgis server\", state=\"unknown\"}*8)",
     "legendFormat": "ArcGIS Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"arcgis license manager\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"running\"}*4) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"arcgis license manager\", state=\"unknown\"}*8)",
     "legendFormat": "ArcGIS License Manager"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"stopped\"}*1) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"start pending\"}*2) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"stop pending\"}*3) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"running\"}*4) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"continue pending\"}*5) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"pause pending\"}*6) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"paused\"}*7) + scalar(windows_service_state{name=\"w3svc\", job=\"apo33wv.teide.int\", state=\"unknown\"}*8)",
     "legendFormat": "Web adaptor - Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - arcgis_backup_created_date_seconds{type=\"full\"} < 2592000 and arcgis_backup_size_bytes{type=\"full\"} > 0",
     "legendFormat": "Backup - Full"
    }
   ]
  },
  {
   "title": "Services types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by(type,instance) (arcgis_service_state)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Nº services",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(arcgis_service_state{cluster=\"started\"} == 1)",
     "legendFormat": "Up"
    },
    {
     "expr": "count(arcgis_service_state{cluster=\"stopped\"} == 1)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Services requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Nº requests" }
   ],
   "targets": [
    {
     "expr": "rate(arcgis_service_trasactions_total[$interval])",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Portal for ArcGIS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(windows_iis_requests_total{site=\"Web adaptor - Portal\"}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ArcGIS Server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(windows_iis_requests_total{site=\"Web adaptor - Server\"}[10m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Servicios",
   "type": "table",
   "description": "The real-time status represents the actual state of a resource. For instance, consider that you have configured the server machine to be STARTED but the machine was abruptly powered off. In this case, its real-time status would be STOPPED. The real-time status information is harvested when the request is made, and it is not persisted.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(arcgis_service_state == 1) by (folder,instance,service_name)"
    },
    {
     "expr": "sum(arcgis_service_state{state=\"started\"} == 1) by(folder,instance,service_name)"
    },
    {
     "expr": "sum(arcgis_service_state{configured_state=\"started\",state=\"stopped\"}) by(folder,instance,service_name)"
    }
   ]
  },
  {
   "title": "Servicios con errores",
   "type": "table",
   "description": "The real-time status represents the actual state of a resource. For instance, consider that you have configured the server machine to be STARTED but the machine was abruptly powered off. In this case, its real-time status would be STOPPED. The real-time status information is harvested when the request is made, and it is not persisted.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "arcgis_service_state{configured_state=\"started\",state=\"stopped\"} == 1"
    }
   ]
  },
  {
   "title": "Licenses",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "argis_expiration_license_seconds * 1000"
    }
   ]
  }
 ]
}