{
 "title": "Backups",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_created_date_seconds{label=\"vente-db\"} < 129600 and backup_size_bytes > 0",
     "legendFormat": "VENTE DB - Last backup"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - arcgis_backup_created_date_seconds{type=\"full\"} < 2592000 and arcgis_backup_size_bytes{type=\"full\"} > 0",
     "legendFormat": "ArcGIS Backup - Full"
    }
   ]
  },
  {
   "title": "Backups ArcGIS Enterprise - Incremental",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "arcgis_backup_created_date_seconds{type=\"incremental\"} * 1000"
    },
    {
     "expr": "arcgis_backup_size_bytes{type=\"incremental\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"ArcGIS Data Store\", type=\"incremental\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"ArcGIS Server\", type=\"incremental\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"Portal for ArcGIS\", type=\"incremental\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"Web GIS components\", type=\"incremental\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - arcgis_backup_created_date_seconds{type=\"incremental\"} < 648000 and arcgis_backup_size_bytes{type=\"incremental\"} > 0",
     "legendFormat": "ArcGIS Backup - Incremental"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table",
   "description": "Histórico de backups",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "backup_size_bytes" },
    {
     "expr": "backup_created_date_seconds*1000"
    },
    { "expr": "backup_duration_seconds_total" }
   ]
  },
  {
   "title": "Backups ArcGIS Enterprise - Full",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "arcgis_backup_created_date_seconds{type=\"full\"} * 1000"
    },
    {
     "expr": "arcgis_backup_size_bytes{type=\"full\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"ArcGIS Data Store\", type=\"full\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"ArcGIS Server\", type=\"full\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"Portal for ArcGIS\", type=\"full\"}"
    },
    {
     "expr": "arcgis_backup_duration_seconds{component=\"Web GIS components\", type=\"full\"}"
    }
   ]
  }
 ]
}