{
 "title": "Windows Server",
 "description": "Windows Prometheus",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Server",
    "query": "label_values(windows_cs_hostname, job)"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])))*100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg((windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}))*100"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\"} / windows_logical_disk_size_bytes{job=~\"$job\"})*100",
     "legendFormat": "{{job}} - {{volume}}"
    }
   ]
  },
  {
   "title": "CPU mode / time",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(windows_cpu_time_total{job=~\"$job\",mode=\"dpc\"}[5m]))",
     "legendFormat": "DPC"
    },
    {
     "expr": "sum(irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[5m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(irate(windows_cpu_time_total{job=~\"$job\",mode=\"user\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(irate(windows_cpu_time_total{job=~\"$job\",mode=\"interrupt\"}[5m]))",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "sum(irate(windows_cpu_time_total{job=~\"$job\",mode=\"privileged\"}[5m]))",
     "legendFormat": "Privileged"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_cs_physical_memory_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "repeat": "host",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - min(windows_system_system_up_time{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_cs_logical_processors{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "System details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"} * 1000)"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (job) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "IOs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (job) (irate(windows_logical_disk_reads_total{job=~\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (job) (irate(windows_logical_disk_writes_total{job=~\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Read/write host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (job) (irate(windows_logical_disk_read_bytes_total{job=~\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (job) (irate(windows_logical_disk_write_bytes_total{job=~\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Latency R/W",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_latency_seconds_total{job=~\"$job\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Read latency {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_write_latency_seconds_total{job=~\"$job\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - R/W latency {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Read/Write drive",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network traffic (max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (job) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Up",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (job) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Down",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network traffic by adapter",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - System threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded{job=~\"$job\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors{job=~\"$job\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded{job=~\"$job\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_received_errors{job=~\"$job\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Free physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}} - Free virtual memory"
    }
   ]
  },
  {
   "title": "Process number",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_os_processes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - Exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Free disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{job=~\"$job\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{job}} - {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}