version: '3.7'

services:
  grafana:
    image: ${IMAGE_NAME:-grafana/grafana}:${IMAGE_TAG:-latest}
    environment:
      GF_SERVER_ROOT_URL: http://${PUBLIC_HOSTNAME}${GRAFANA_PATH}
      GF_SERVER_SERVE_FROM_SUB_PATH:
      GF_SERVER_DOMAIN: ${PUBLIC_HOSTNAME}
      GF_PATHS_DATA:
      GF_PATHS_PROVISIONING:
      GF_INSTALL_PLUGINS:
      GF_SERVER_HTTP_PORT:
      GF_SERVER_ENABLE_GZIP:
      GF_SECURITY_ADMIN_USER:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_USERS_ALLOW_SIGN_UP:
      GF_USERS_AUTO_ASSIGN_ORG:
      GF_USERS_AUTO_ASSIGN_ORG_ID:
      GF_USERS_AUTO_ASSIGN_ORG_ROLE:
      GF_SMTP_ENABLED:
      GF_SMTP_FROM_ADDRESS:
      GF_SMTP_FROM_NAME:
      GF_SMTP_HOST:
      GF_SMTP_SKIP_VERIFY:
      GF_SMTP_USER:
      GF_SMTP_PASSWORD:
      GF_LOG_MODE:
      GF_LOG_LEVEL:
      DASHBOARDS_PATH:
      PROMETHEUS_URL:
    networks:
      log-net:
      monitoring-net:
      traefik-net:
    volumes:
      - grafana-data-vol:${GF_PATHS_DATA}
    configs:
      - source: datasources-config
        target: ${GF_PATHS_PROVISIONING}/datasources/datasources.yml
      - source: dashboards-providers-config
        target: ${GF_PATHS_PROVISIONING}/dashboards/dashboards_providers.yml
      - source: nodes-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-nodes.json
      - source: arcgis-enterprise-dashboard-config
        target: ${DASHBOARDS_PATH}/arcgis-enterprise.json
      - source: services-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-services.json
      - source: prometheus-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-prometheus.json
      - source: docker-dashboard-config
        target: ${DASHBOARDS_PATH}/docker.json
      - source: postgres-dashboard-config
        target: ${DASHBOARDS_PATH}/postgres.json
      - source: traefik-dashboard-config
        target: ${DASHBOARDS_PATH}/traefik.json
      - source: windows-server-dashboard-config
        target: ${DASHBOARDS_PATH}/windows-server.json
      - source: windows-server-nodes-dashboard-config
        target: ${DASHBOARDS_PATH}/windows-server-nodes.json
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.grafana.entrypoints: http
        traefik.http.routers.grafana.rule: Host(`${PUBLIC_HOSTNAME}`) && PathPrefix(`${GRAFANA_PATH}`)
        traefik.http.services.grafana.loadbalancer.server.port: '${GF_SERVER_HTTP_PORT}'
        traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes: ${GRAFANA_PATH}
        traefik.http.routers.grafana.middlewares: grafana-stripprefix
        traefik.http.routers.grafana.service: grafana
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  log-net:
    name: ${LOG_NET_NAME:-log-net}
    driver: ${LOG_NET_DRIVER:-overlay}
    external: true

  monitoring-net:
    name: ${MONITORING_NET_NAME:-monitoring-net}
    driver: ${MONITORING_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  datasources-config:
    name: ${DATASOURCES_CONFIG_NAME:-grafana-datasources}
    file: ./config/datasources.yml

  dashboards-providers-config:
    name: ${DASHBOARDS_PROVIDERS_CONFIG_NAME:-grafana-dashboards-providers}
    file: ./config/dashboards_providers.yml

  nodes-dashboard-config:
    name: ${NODES_DASHBOARD_CONFIG_NAME:-grafana-nodes-dashboard}
    file: ./config/dashboards/swarmprom-nodes.json
  
  arcgis-enterprise-dashboard-config:
    name: ${ARCGIS_ENTERPRISE_DASHBOARD_CONFIG_NAME:-grafana-arcgis-enterprise-dashboard}
    file: ./config/dashboards/arcgis-enterprise.json

  services-dashboard-config:
    name: ${SERVICES_DASHBOARD_CONFIG_NAME:-grafana-services-dashboard}
    file: ./config/dashboards/swarmprom-services.json

  prometheus-dashboard-config:
    name: ${PROMETHEUS_DASHBOARD_CONFIG_NAME:-grafana-prometheus-dashboard}
    file: ./config/dashboards/swarmprom-prometheus.json

  docker-dashboard-config:
    name: ${DOCKER_DASHBOARD_CONFIG_NAME:-grafana-docker-dashboard}
    file: ./config/dashboards/docker.json

  postgres-dashboard-config:
    name: ${POSTGRES_DASHBOARD_CONFIG_NAME:-grafana-postgres-dashboard}
    file: ./config/dashboards/postgres.json

  traefik-dashboard-config:
    name: ${TRAEFIK_DASHBOARD_CONFIG_NAME:-grafana-traefik-dashboard}
    file: ./config/dashboards/traefik.json

  windows-server-dashboard-config:
    name: ${WINDOWS_SERVER_DASHBOARD_CONFIG_NAME:-grafana-windows-server-dashboard}
    file: ./config/dashboards/windows-server.json

  windows-server-nodes-dashboard-config:
    name: ${WINDOWS_SERVER_NODES_DASHBOARD_CONFIG_NAME:-grafana-windows-server-nodes-dashboard}
    file: ./config/dashboards/windows-server-nodes.json

volumes:
  grafana-data-vol:
    name: ${GRAFANA_DATA_VOL_NAME}